name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  cargo-build:
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.57.0
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: |-
        rustup component add clippy
        cargo clippy
    - name: Run tests
      run: cargo test --verbose
    - name: Run wasm tests
      run: |-
        rustup target add wasm32-unknown-unknown
        cargo install wasm-pack
        cargo build
        wasm-pack test --node
      working-directory: ./cron_cal_wasm

  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "14"
    - run: npm install
      working-directory: ./cron_cal_wasm
    - run: npm run lint
      working-directory: ./cron_cal_wasm
