name: gh pages deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: latest
    - uses: actions/setup-node@v3
      with:
        node-version: "14"
    - run: npm install
      working-directory: ./cron_cal_wasm
    - run: npm run build
      working-directory: ./cron_cal_wasm
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cron_cal_wasm/public/
